import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtinModules from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Agent Lock Guard - Multi-Agent Concurrency & Collision Guard for Obsidian
*/
`;

const prod = process.argv[2] !== "dev";

// Target vault plugins folder
const vaultPluginDir = path.resolve("../Obsidian WorkOS/.obsidian/plugins/agent-lock-guard");
const localDistDir = path.resolve("./dist");

[vaultPluginDir, localDistDir].forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

// Copy manifest.json & styles.css
function copyAssets() {
  const manifestSrc = path.resolve("./manifest.json");
  const stylesSrc = path.resolve("./src/styles.css");

  [vaultPluginDir, localDistDir].forEach(targetDir => {
    if (fs.existsSync(manifestSrc)) {
      fs.copyFileSync(manifestSrc, path.join(targetDir, "manifest.json"));
    }
    if (fs.existsSync(stylesSrc)) {
      fs.copyFileSync(stylesSrc, path.join(targetDir, "styles.css"));
    }
  });
  console.log("Assets copied to Vault and dist.");
}

copyAssets();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(vaultPluginDir, "main.js"),
});

if (prod) {
  await context.rebuild();
  // Also copy main.js to local dist
  if (fs.existsSync(path.join(vaultPluginDir, "main.js"))) {
    fs.copyFileSync(path.join(vaultPluginDir, "main.js"), path.join(localDistDir, "main.js"));
  }
  await context.dispose();
  console.log("Production build finished successfully!");
} else {
  await context.watch();
  console.log("Watching for changes...");
}
